version: '3'

services:
  db:
    image: postgres
    ports:
        - "5432:5432"       
  redis:
    image: redis
    command: redis-server
  web:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - .:/chat
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis